SELECT c FROM
(SELECT Essn FROM (SELECT Essn, COUNT(Bdate) AS c
FROM DEPENDENT
WHERE Essn IN
(SELECT Mgr_ssn FROM DEPARTMENT WHERE Dnumber IN
(SELECT Dnumber FROM (SELECT Dnumber, COUNT(Dlocation) as cnt
FROM DEPT_LOCATIONS
GROUP BY Dnumber
HAVING COUNT(Dlocation) >= 2) AS loc)
GROUP BY Essn)))